## Apache Tomcat v8.5.31 with latest Oracle JDK 8 Dockerfile ##
# Dockerfile Maintained By Ahmed Choukri - Latest update June 14 2018
# tomcat package http://www.goodbrains.ca/downloads/apache-tomcat-8.5.31.tar.gz
# OS Ubuntu:18.04 LTS


FROM docker.io/ubuntu:18.04

MAINTAINER Ahmed Choukri  "ahmedchoukri@gmail.com"

LABEL description="Apache Tomcat v8.5.23 with Oracle JDK 8"

ENV TOMCAT_TARBALL_URL http://www.goodbrains.ca/downloads/apache-tomcat-8.5.31.tar.gz

ENV WAR_FILE WebAppX.war

ENV CATALINA_HOME /opt/AppServer/tomcat

ENV PATH $CATALINA_HOME/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common wget debconf-utils && add-apt-repository -y ppa:webupd8team/java

# Auto Acccept Oracle Java 8 License
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections \
&& echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections

RUN apt-get update && apt-get install -y oracle-java8-installer

RUN mkdir -p /opt/AppServer

WORKDIR /opt/AppServer

RUN wget $TOMCAT_TARBALL_URL

RUN tar -xvf apache-tomcat-8.5.31.tar.gz && mv apache-tomcat-8.5.31 tomcat && rm -f apache-tomcat-8.5.31.tar.gz \
&& rm -fr $CATALINA_HOME/webapps/examples

# Change tomcat env variables
COPY setenv.sh /opt/AppServer/tomcat/bin/setenv.sh
COPY $WAR_FILE /opt/AppServer/tomcat/webapps/$WAR_FILE

RUN cd /opt/AppServer/tomcat/bin && chmod +x *.sh

EXPOSE 8080

CMD ["catalina.sh", "run"]

