## Apache Tomcat v8.5.6 with latest Oracle JDK 8 Dockerfile ##
# Dockerfile Maintained By Ahmed Choukri - Latest update Nov 6 2016 
# tomcat package http://apache.mirror.vexxhost.com/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz
# OS Ubuntu:16.04 LTS


FROM ubuntu:latest

MAINTAINER Ahmed Choukri  "ahmedchoukri@gmail.com"

LABEL description="Apache Tomcat v8.5.6 with Oracle JDK 8"

ENV TOMCAT_TARBALL_URL http://apache.mirror.vexxhost.com/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz

ENV CATALINA_HOME /opt/AppServer/tomcat

ENV PATH $CATALINA_HOME/bin:$PATH

RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common wget debconf-utils && add-apt-repository -y ppa:webupd8team/java

# Auto Acccept Oracle Java 8 License
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections \
&& echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 seen true" | debconf-set-selections

RUN apt-get update && apt-get install -y oracle-java8-installer

RUN mkdir -p /opt/AppServer

WORKDIR /opt/AppServer

RUN wget $TOMCAT_TARBALL_URL

RUN tar -xvf apache-tomcat-8.5.6.tar.gz && mv apache-tomcat-8.5.6 tomcat && rm -f apache-tomcat-8.5.6.tar.gz \
&& rm -fr /opt/AppServer/tomcat/webapps/examples 

# Change tomcat env variables
COPY setenv.sh /opt/AppServer/tomcat/bin/setenv.sh
 
RUN cd /opt/AppServer/tomcat/bin && chmod +x *.sh

# Map to /opt/tomcat/webapps --> this is where you deploy .war file on your local server 
VOLUME /opt/AppServer/tomcat/webapps

# Map to /var/log/tomcat --> tomcat logs on your local server
VOLUME /opt/AppServer/tomcat/logs

EXPOSE 8080

CMD ["catalina.sh", "run"]
